// Generated by CoffeeScript 2.5.1
export default async(func, ...args) => {
  var err;
  try {
    return (await func(...args));
  } catch (error) {
    err = error;
    return console.error(err);
  }
};

//# sourceMappingURL=index.js.map
