// Generated by CoffeeScript 2.5.1
var DCron, HCron, MCron;

export var Cron = class Cron {
  constructor(interval1) {
    this.interval = interval1;
    this.job = [];
    this.timer = setInterval(this.run.bind(this), this.interval);
  }

  run() {
    return console.log(this.job);
  }

  add(interval, job, now = true) {
    if (now) {
      job();
    }
    return this.job.push([interval, job, interval]);
  }

};

MCron = new Cron(6000);

HCron = new Cron(3600000);

DCron = new Cron(3600000 * 24);

export var mcron = MCron.add.bind(MCron);

export var hcron = HCron.add.bind(HCron);

export var dcron = DCron.add.bind(DCron);

//# sourceMappingURL=index.js.map
