// Generated by CoffeeScript 2.5.1
import {
  mcron
} from './index.js';

(() => {
  return mcron(1, () => {
    return console.log(new Date().toLocaleString());
  });
})();

//# sourceMappingURL=index_test.js.map
